apiVersion: apps/v1
kind: Deployment
metadata:
  name: guild-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      name: guild
  template:
    metadata:
      labels:
        name: guild
    spec:
      containers:
      - name: guild
        image: 425409/guildservice:main
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9091