apiVersion: apps/v1
kind: Deployment
metadata:
  name: guild-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guild
  template:
    metadata:
      labels:
        app: guild
    spec:
      containers:
        - name: guild
          image: 425409/guildservice:main
---
apiVersion: v1
kind: Service
metadata:
  name: guild-srv
spec:
  selector:
    app: guild
  ports:
    - name: guild
      protocol: TCP
      port: 9091
      targetPort: 9091